// @ts-nocheck
// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "../spacetimedb-shim";

export default __t.row({
  alertKey: __t.string().primaryKey().name("alert_key"),
  alertId: __t.option(__t.i64()).name("alert_id"),
  alertType: __t.option(__t.string()).name("alert_type"),
  cause: __t.option(__t.string()),
  startTime: __t.option(__t.string()).name("start_time"),
  endTime: __t.option(__t.string()).name("end_time"),
  mode: __t.option(__t.string()),
  lineCommercialName: __t.option(__t.string()).name("line_commercial_name"),
  lineCustomerName: __t.option(__t.string()).name("line_customer_name"),
  title: __t.option(__t.string()),
  message: __t.option(__t.string()),
  lastUpdate: __t.option(__t.string()).name("last_update"),
  severityType: __t.option(__t.string()).name("severity_type"),
  severityLevel: __t.option(__t.i64()).name("severity_level"),
  objectType: __t.option(__t.string()).name("object_type"),
  objectList: __t.option(__t.string()).name("object_list"),
});
