// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  idStation: __t.string().primaryKey().name("id_station"),
  name: __t.string(),
  address: __t.option(__t.string()),
  commune: __t.option(__t.string()),
  latitude: __t.f64(),
  longitude: __t.f64(),
  nbEmplacements: __t.i64().name("nb_emplacements"),
  typeAutopartage: __t.option(__t.string()).name("type_autopartage"),
  lastUpdate: __t.option(__t.string()).name("last_update"),
  recordedAt: __t.timestamp().name("recorded_at"),
});
