// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  datedVehicleJourneyRef: __t.string().primaryKey().name("dated_vehicle_journey_ref"),
  recordedAtTime: __t.timestamp().name("recorded_at_time"),
  lineRef: __t.option(__t.string()).name("line_ref"),
  directionRef: __t.option(__t.string()).name("direction_ref"),
  destinationRef: __t.option(__t.string()).name("destination_ref"),
  lineSortCode: __t.option(__t.string()).name("line_sort_code"),
});
