// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  callId: __t.string().primaryKey().name("call_id"),
  recordedAtTime: __t.timestamp().name("recorded_at_time"),
  datedVehicleJourneyRef: __t.string().name("dated_vehicle_journey_ref"),
  stopPointRef: __t.option(__t.string()).name("stop_point_ref"),
  gtfsStopId: __t.option(__t.string()).name("gtfs_stop_id"),
  stopPointName: __t.option(__t.string()).name("stop_point_name"),
  aimedArrivalTime: __t.option(__t.string()).name("aimed_arrival_time"),
  expectedArrivalTime: __t.option(__t.string()).name("expected_arrival_time"),
  aimedDepartureTime: __t.option(__t.string()).name("aimed_departure_time"),
  expectedDepartureTime: __t.option(__t.string()).name("expected_departure_time"),
  stopOrder: __t.option(__t.i64()).name("stop_order"),
});
