// @ts-nocheck
// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "../spacetimedb-shim";

export default __t.row({
  transferId: __t.string().primaryKey().name("transfer_id"),
  fromStopId: __t.option(__t.string()).name("from_stop_id"),
  toStopId: __t.option(__t.string()).name("to_stop_id"),
  transferType: __t.option(__t.string()).name("transfer_type"),
  minTransferTime: __t.option(__t.string()).name("min_transfer_time"),
});
