// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  serviceId: __t.string().primaryKey().name("service_id"),
  monday: __t.option(__t.string()),
  tuesday: __t.option(__t.string()),
  wednesday: __t.option(__t.string()),
  thursday: __t.option(__t.string()),
  friday: __t.option(__t.string()),
  saturday: __t.option(__t.string()),
  sunday: __t.option(__t.string()),
  startDate: __t.option(__t.string()).name("start_date"),
  endDate: __t.option(__t.string()).name("end_date"),
});
