// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  calendarDateId: __t.string().primaryKey().name("calendar_date_id"),
  serviceId: __t.option(__t.string()).name("service_id"),
  date: __t.option(__t.string()),
  exceptionType: __t.option(__t.string()).name("exception_type"),
});
