// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  shapePointId: __t.string().primaryKey().name("shape_point_id"),
  shapeId: __t.option(__t.string()).name("shape_id"),
  shapePtLat: __t.option(__t.string()).name("shape_pt_lat"),
  shapePtLon: __t.option(__t.string()).name("shape_pt_lon"),
  shapePtSequence: __t.option(__t.string()).name("shape_pt_sequence"),
  shapeDistTraveled: __t.option(__t.string()).name("shape_dist_traveled"),
});
