// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  stopTimeId: __t.string().primaryKey().name("stop_time_id"),
  tripId: __t.option(__t.string()).name("trip_id"),
  arrivalTime: __t.option(__t.string()).name("arrival_time"),
  departureTime: __t.option(__t.string()).name("departure_time"),
  stopId: __t.option(__t.string()).name("stop_id"),
  stopSequence: __t.option(__t.string()).name("stop_sequence"),
  stopHeadsign: __t.option(__t.string()).name("stop_headsign"),
  pickupType: __t.option(__t.string()).name("pickup_type"),
  dropOffType: __t.option(__t.string()).name("drop_off_type"),
  shapeDistTraveled: __t.option(__t.string()).name("shape_dist_traveled"),
  timepoint: __t.option(__t.string()),
});
