// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  routeId: __t.string().primaryKey().name("route_id"),
  agencyId: __t.option(__t.string()).name("agency_id"),
  routeShortName: __t.option(__t.string()).name("route_short_name"),
  routeLongName: __t.option(__t.string()).name("route_long_name"),
  routeDesc: __t.option(__t.string()).name("route_desc"),
  routeType: __t.option(__t.string()).name("route_type"),
  routeUrl: __t.option(__t.string()).name("route_url"),
  routeColor: __t.option(__t.string()).name("route_color"),
  routeTextColor: __t.option(__t.string()).name("route_text_color"),
  routeSortOrder: __t.option(__t.string()).name("route_sort_order"),
});
