// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  stopId: __t.string().primaryKey().name("stop_id"),
  stopCode: __t.option(__t.string()).name("stop_code"),
  stopName: __t.option(__t.string()).name("stop_name"),
  stopDesc: __t.option(__t.string()).name("stop_desc"),
  stopLat: __t.option(__t.string()).name("stop_lat"),
  stopLon: __t.option(__t.string()).name("stop_lon"),
  zoneId: __t.option(__t.string()).name("zone_id"),
  stopUrl: __t.option(__t.string()).name("stop_url"),
  locationType: __t.option(__t.string()).name("location_type"),
  parentStation: __t.option(__t.string()).name("parent_station"),
  stopTimezone: __t.option(__t.string()).name("stop_timezone"),
  wheelchairBoarding: __t.option(__t.string()).name("wheelchair_boarding"),
  levelId: __t.option(__t.string()).name("level_id"),
  platformCode: __t.option(__t.string()).name("platform_code"),
});
