// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  tripId: __t.string().primaryKey().name("trip_id"),
  routeId: __t.option(__t.string()).name("route_id"),
  serviceId: __t.option(__t.string()).name("service_id"),
  tripHeadsign: __t.option(__t.string()).name("trip_headsign"),
  tripShortName: __t.option(__t.string()).name("trip_short_name"),
  directionId: __t.option(__t.string()).name("direction_id"),
  blockId: __t.option(__t.string()).name("block_id"),
  shapeId: __t.option(__t.string()).name("shape_id"),
  wheelchairAccessible: __t.option(__t.string()).name("wheelchair_accessible"),
  bikesAllowed: __t.option(__t.string()).name("bikes_allowed"),
});
