// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  agencyId: __t.string().primaryKey().name("agency_id"),
  agencyName: __t.option(__t.string()).name("agency_name"),
  agencyUrl: __t.option(__t.string()).name("agency_url"),
  agencyTimezone: __t.option(__t.string()).name("agency_timezone"),
  agencyLang: __t.option(__t.string()).name("agency_lang"),
  agencyPhone: __t.option(__t.string()).name("agency_phone"),
  agencyFareUrl: __t.option(__t.string()).name("agency_fare_url"),
  agencyEmail: __t.option(__t.string()).name("agency_email"),
});
