// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  feedId: __t.u64().primaryKey().name("feed_id"),
  feedPublisherName: __t.option(__t.string()).name("feed_publisher_name"),
  feedPublisherUrl: __t.option(__t.string()).name("feed_publisher_url"),
  feedLang: __t.option(__t.string()).name("feed_lang"),
  feedStartDate: __t.option(__t.string()).name("feed_start_date"),
  feedEndDate: __t.option(__t.string()).name("feed_end_date"),
  feedVersion: __t.option(__t.string()).name("feed_version"),
});
