// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 2.2.0 (commit eb11e2f5c41dce6979715ad407996270d61329f6).

/* eslint-disable */
/* tslint:disable */
import {
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TypeBuilder as __TypeBuilder,
  Uuid as __Uuid,
  convertToAccessorMap as __convertToAccessorMap,
  makeQueryBuilder as __makeQueryBuilder,
  procedureSchema as __procedureSchema,
  procedures as __procedures,
  reducerSchema as __reducerSchema,
  reducers as __reducers,
  schema as __schema,
  t as __t,
  table as __table,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type DbConnectionConfig as __DbConnectionConfig,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type Infer as __Infer,
  type QueryBuilder as __QueryBuilder,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type RemoteModule as __RemoteModule,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
  type SubscriptionHandleImpl as __SubscriptionHandleImpl,
} from "spacetimedb";

// Import all reducer arg schemas

// Import all procedure arg schemas
import * as CalculateJourneyProcedure from "./calculate_journey_procedure";
import * as IngestAutopartageProcedure from "./ingest_autopartage_procedure";
import * as IngestGtfsProcedure from "./ingest_gtfs_procedure";
import * as IngestPublicToiletsProcedure from "./ingest_public_toilets_procedure";
import * as IngestRealtimeProcedure from "./ingest_realtime_procedure";
import * as IngestRealtimePayloadProcedure from "./ingest_realtime_payload_procedure";
import * as IngestStaticProcedure from "./ingest_static_procedure";
import * as IngestStaticPayloadProcedure from "./ingest_static_payload_procedure";
import * as IngestVelovProcedure from "./ingest_velov_procedure";
import * as PurgeIngestionRunsProcedure from "./purge_ingestion_runs_procedure";
import * as PurgeRealtimeProcedure from "./purge_realtime_procedure";
import * as SetConfigProcedure from "./set_config_procedure";
import * as SetConfigPlainProcedure from "./set_config_plain_procedure";

// Import all table schema definitions
import AlertsRow from "./alerts_table";
import AutopartageStationsRow from "./autopartage_stations_table";
import ConfigRow from "./config_table";
import EstimatedCallsCurrentRow from "./estimated_calls_current_table";
import EstimatedVehicleJourneysCurrentRow from "./estimated_vehicle_journeys_current_table";
import GtfsAgencyRow from "./gtfs_agency_table";
import GtfsCalendarRow from "./gtfs_calendar_table";
import GtfsCalendarDatesRow from "./gtfs_calendar_dates_table";
import GtfsFeedInfoRow from "./gtfs_feed_info_table";
import GtfsRoutesRow from "./gtfs_routes_table";
import GtfsShapesRow from "./gtfs_shapes_table";
import GtfsStopTimesRow from "./gtfs_stop_times_table";
import GtfsStopsRow from "./gtfs_stops_table";
import GtfsTransfersRow from "./gtfs_transfers_table";
import GtfsTripsRow from "./gtfs_trips_table";
import IngestionRunsRow from "./ingestion_runs_table";
import LineIconMappingRow from "./line_icon_mapping_table";
import LinesRow from "./lines_table";
import PricingZonesRow from "./pricing_zones_table";
import PublicToiletsRow from "./public_toilets_table";
import StationsRow from "./stations_table";
import StopRefNameCacheRow from "./stop_ref_name_cache_table";
import StopsRow from "./stops_table";
import VehiclePositionsCurrentRow from "./vehicle_positions_current_table";
import VelovStationsRow from "./velov_stations_table";

/** Type-only namespace exports for generated type groups. */

/** The schema information for all tables in this module. This is defined the same was as the tables would have been defined in the server. */
const tablesSchema = __schema({
  alerts: __table({
    name: 'alerts',
    indexes: [
      { accessor: 'alert_key', name: 'alerts_alert_key_idx_btree', algorithm: 'btree', columns: [
        'alertKey',
      ] },
    ],
    constraints: [
      { name: 'alerts_alert_key_key', constraint: 'unique', columns: ['alertKey'] },
    ],
  }, AlertsRow),
  autopartage_stations: __table({
    name: 'autopartage_stations',
    indexes: [
      { accessor: 'id_station', name: 'autopartage_stations_id_station_idx_btree', algorithm: 'btree', columns: [
        'idStation',
      ] },
    ],
    constraints: [
      { name: 'autopartage_stations_id_station_key', constraint: 'unique', columns: ['idStation'] },
    ],
  }, AutopartageStationsRow),
  config: __table({
    name: 'config',
    indexes: [
      { accessor: 'id', name: 'config_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'config_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, ConfigRow),
  estimated_calls_current: __table({
    name: 'estimated_calls_current',
    indexes: [
      { accessor: 'call_id', name: 'estimated_calls_current_call_id_idx_btree', algorithm: 'btree', columns: [
        'callId',
      ] },
      { accessor: 'dated_vehicle_journey_ref', name: 'estimated_calls_current_dated_vehicle_journey_ref_idx_btree', algorithm: 'btree', columns: [
        'datedVehicleJourneyRef',
      ] },
      { accessor: 'recorded_at_time', name: 'estimated_calls_current_recorded_at_time_idx_btree', algorithm: 'btree', columns: [
        'recordedAtTime',
      ] },
    ],
    constraints: [
      { name: 'estimated_calls_current_call_id_key', constraint: 'unique', columns: ['callId'] },
    ],
  }, EstimatedCallsCurrentRow),
  estimated_vehicle_journeys_current: __table({
    name: 'estimated_vehicle_journeys_current',
    indexes: [
      { accessor: 'dated_vehicle_journey_ref', name: 'estimated_vehicle_journeys_current_dated_vehicle_journey_ref_idx_btree', algorithm: 'btree', columns: [
        'datedVehicleJourneyRef',
      ] },
      { accessor: 'recorded_at_time', name: 'estimated_vehicle_journeys_current_recorded_at_time_idx_btree', algorithm: 'btree', columns: [
        'recordedAtTime',
      ] },
    ],
    constraints: [
      { name: 'estimated_vehicle_journeys_current_dated_vehicle_journey_ref_key', constraint: 'unique', columns: ['datedVehicleJourneyRef'] },
    ],
  }, EstimatedVehicleJourneysCurrentRow),
  gtfs_agency: __table({
    name: 'gtfs_agency',
    indexes: [
      { accessor: 'agency_id', name: 'gtfs_agency_agency_id_idx_btree', algorithm: 'btree', columns: [
        'agencyId',
      ] },
    ],
    constraints: [
      { name: 'gtfs_agency_agency_id_key', constraint: 'unique', columns: ['agencyId'] },
    ],
  }, GtfsAgencyRow),
  gtfs_calendar: __table({
    name: 'gtfs_calendar',
    indexes: [
      { accessor: 'service_id', name: 'gtfs_calendar_service_id_idx_btree', algorithm: 'btree', columns: [
        'serviceId',
      ] },
    ],
    constraints: [
      { name: 'gtfs_calendar_service_id_key', constraint: 'unique', columns: ['serviceId'] },
    ],
  }, GtfsCalendarRow),
  gtfs_calendar_dates: __table({
    name: 'gtfs_calendar_dates',
    indexes: [
      { accessor: 'calendar_date_id', name: 'gtfs_calendar_dates_calendar_date_id_idx_btree', algorithm: 'btree', columns: [
        'calendarDateId',
      ] },
    ],
    constraints: [
      { name: 'gtfs_calendar_dates_calendar_date_id_key', constraint: 'unique', columns: ['calendarDateId'] },
    ],
  }, GtfsCalendarDatesRow),
  gtfs_feed_info: __table({
    name: 'gtfs_feed_info',
    indexes: [
      { accessor: 'feed_id', name: 'gtfs_feed_info_feed_id_idx_btree', algorithm: 'btree', columns: [
        'feedId',
      ] },
    ],
    constraints: [
      { name: 'gtfs_feed_info_feed_id_key', constraint: 'unique', columns: ['feedId'] },
    ],
  }, GtfsFeedInfoRow),
  gtfs_routes: __table({
    name: 'gtfs_routes',
    indexes: [
      { accessor: 'route_id', name: 'gtfs_routes_route_id_idx_btree', algorithm: 'btree', columns: [
        'routeId',
      ] },
    ],
    constraints: [
      { name: 'gtfs_routes_route_id_key', constraint: 'unique', columns: ['routeId'] },
    ],
  }, GtfsRoutesRow),
  gtfs_shapes: __table({
    name: 'gtfs_shapes',
    indexes: [
      { accessor: 'shape_point_id', name: 'gtfs_shapes_shape_point_id_idx_btree', algorithm: 'btree', columns: [
        'shapePointId',
      ] },
    ],
    constraints: [
      { name: 'gtfs_shapes_shape_point_id_key', constraint: 'unique', columns: ['shapePointId'] },
    ],
  }, GtfsShapesRow),
  gtfs_stop_times: __table({
    name: 'gtfs_stop_times',
    indexes: [
      { accessor: 'stop_time_id', name: 'gtfs_stop_times_stop_time_id_idx_btree', algorithm: 'btree', columns: [
        'stopTimeId',
      ] },
    ],
    constraints: [
      { name: 'gtfs_stop_times_stop_time_id_key', constraint: 'unique', columns: ['stopTimeId'] },
    ],
  }, GtfsStopTimesRow),
  gtfs_stops: __table({
    name: 'gtfs_stops',
    indexes: [
      { accessor: 'stop_id', name: 'gtfs_stops_stop_id_idx_btree', algorithm: 'btree', columns: [
        'stopId',
      ] },
    ],
    constraints: [
      { name: 'gtfs_stops_stop_id_key', constraint: 'unique', columns: ['stopId'] },
    ],
  }, GtfsStopsRow),
  gtfs_transfers: __table({
    name: 'gtfs_transfers',
    indexes: [
      { accessor: 'transfer_id', name: 'gtfs_transfers_transfer_id_idx_btree', algorithm: 'btree', columns: [
        'transferId',
      ] },
    ],
    constraints: [
      { name: 'gtfs_transfers_transfer_id_key', constraint: 'unique', columns: ['transferId'] },
    ],
  }, GtfsTransfersRow),
  gtfs_trips: __table({
    name: 'gtfs_trips',
    indexes: [
      { accessor: 'trip_id', name: 'gtfs_trips_trip_id_idx_btree', algorithm: 'btree', columns: [
        'tripId',
      ] },
    ],
    constraints: [
      { name: 'gtfs_trips_trip_id_key', constraint: 'unique', columns: ['tripId'] },
    ],
  }, GtfsTripsRow),
  ingestion_runs: __table({
    name: 'ingestion_runs',
    indexes: [
      { accessor: 'id', name: 'ingestion_runs_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'started_at', name: 'ingestion_runs_started_at_idx_btree', algorithm: 'btree', columns: [
        'startedAt',
      ] },
    ],
    constraints: [
      { name: 'ingestion_runs_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, IngestionRunsRow),
  line_icon_mapping: __table({
    name: 'line_icon_mapping',
    indexes: [
      { accessor: 'code_ligne', name: 'line_icon_mapping_code_ligne_idx_btree', algorithm: 'btree', columns: [
        'codeLigne',
      ] },
    ],
    constraints: [
      { name: 'line_icon_mapping_code_ligne_key', constraint: 'unique', columns: ['codeLigne'] },
    ],
  }, LineIconMappingRow),
  lines: __table({
    name: 'lines',
    indexes: [
      { accessor: 'id', name: 'lines_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'lines_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, LinesRow),
  pricing_zones: __table({
    name: 'pricing_zones',
    indexes: [
      { accessor: 'id', name: 'pricing_zones_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'pricing_zones_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, PricingZonesRow),
  public_toilets: __table({
    name: 'public_toilets',
    indexes: [
      { accessor: 'id', name: 'public_toilets_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'public_toilets_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, PublicToiletsRow),
  stations: __table({
    name: 'stations',
    indexes: [
      { accessor: 'id', name: 'stations_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'stations_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, StationsRow),
  stop_ref_name_cache: __table({
    name: 'stop_ref_name_cache',
    indexes: [
      { accessor: 'stop_ref', name: 'stop_ref_name_cache_stop_ref_idx_btree', algorithm: 'btree', columns: [
        'stopRef',
      ] },
    ],
    constraints: [
      { name: 'stop_ref_name_cache_stop_ref_key', constraint: 'unique', columns: ['stopRef'] },
    ],
  }, StopRefNameCacheRow),
  stops: __table({
    name: 'stops',
    indexes: [
      { accessor: 'id', name: 'stops_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'stops_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, StopsRow),
  vehicle_positions_current: __table({
    name: 'vehicle_positions_current',
    indexes: [
      { accessor: 'line_ref', name: 'vehicle_positions_current_line_ref_idx_btree', algorithm: 'btree', columns: [
        'lineRef',
      ] },
      { accessor: 'recorded_at_time', name: 'vehicle_positions_current_recorded_at_time_idx_btree', algorithm: 'btree', columns: [
        'recordedAtTime',
      ] },
      { accessor: 'vehicle_ref', name: 'vehicle_positions_current_vehicle_ref_idx_btree', algorithm: 'btree', columns: [
        'vehicleRef',
      ] },
    ],
    constraints: [
      { name: 'vehicle_positions_current_vehicle_ref_key', constraint: 'unique', columns: ['vehicleRef'] },
    ],
  }, VehiclePositionsCurrentRow),
  velov_stations: __table({
    name: 'velov_stations',
    indexes: [
      { accessor: 'number', name: 'velov_stations_number_idx_btree', algorithm: 'btree', columns: [
        'number',
      ] },
    ],
    constraints: [
      { name: 'velov_stations_number_key', constraint: 'unique', columns: ['number'] },
    ],
  }, VelovStationsRow),
});

/** The schema information for all reducers in this module. This is defined the same way as the reducers would have been defined in the server, except the body of the reducer is omitted in code generation. */
const reducersSchema = __reducers(
);

/** The schema information for all procedures in this module. This is defined the same way as the procedures would have been defined in the server. */
const proceduresSchema = __procedures(
  __procedureSchema("calculate_journey", CalculateJourneyProcedure.params, CalculateJourneyProcedure.returnType),
  __procedureSchema("ingest_autopartage", IngestAutopartageProcedure.params, IngestAutopartageProcedure.returnType),
  __procedureSchema("ingest_gtfs", IngestGtfsProcedure.params, IngestGtfsProcedure.returnType),
  __procedureSchema("ingest_public_toilets", IngestPublicToiletsProcedure.params, IngestPublicToiletsProcedure.returnType),
  __procedureSchema("ingest_realtime", IngestRealtimeProcedure.params, IngestRealtimeProcedure.returnType),
  __procedureSchema("ingest_realtime_payload", IngestRealtimePayloadProcedure.params, IngestRealtimePayloadProcedure.returnType),
  __procedureSchema("ingest_static", IngestStaticProcedure.params, IngestStaticProcedure.returnType),
  __procedureSchema("ingest_static_payload", IngestStaticPayloadProcedure.params, IngestStaticPayloadProcedure.returnType),
  __procedureSchema("ingest_velov", IngestVelovProcedure.params, IngestVelovProcedure.returnType),
  __procedureSchema("purge_ingestion_runs", PurgeIngestionRunsProcedure.params, PurgeIngestionRunsProcedure.returnType),
  __procedureSchema("purge_realtime", PurgeRealtimeProcedure.params, PurgeRealtimeProcedure.returnType),
  __procedureSchema("set_config", SetConfigProcedure.params, SetConfigProcedure.returnType),
  __procedureSchema("set_config_plain", SetConfigPlainProcedure.params, SetConfigPlainProcedure.returnType),
);

/** The remote SpacetimeDB module schema, both runtime and type information. */
const REMOTE_MODULE = {
  versionInfo: {
    cliVersion: "2.2.0" as const,
  },
  tables: tablesSchema.schemaType.tables,
  reducers: reducersSchema.reducersType.reducers,
  ...proceduresSchema,
} satisfies __RemoteModule<
  typeof tablesSchema.schemaType,
  typeof reducersSchema.reducersType,
  typeof proceduresSchema
>;

/** The tables available in this remote SpacetimeDB module. Each table reference doubles as a query builder. */
export const tables: __QueryBuilder<typeof tablesSchema.schemaType> = __makeQueryBuilder(tablesSchema.schemaType);

/** The reducers available in this remote SpacetimeDB module. */
export const reducers = __convertToAccessorMap(reducersSchema.reducersType.reducers);

/** The procedures available in this remote SpacetimeDB module. */
export const procedures = __convertToAccessorMap(proceduresSchema.procedures);

/** The context type returned in callbacks for all possible events. */
export type EventContext = __EventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for reducer events. */
export type ReducerEventContext = __ReducerEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for subscription events. */
export type SubscriptionEventContext = __SubscriptionEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for error events. */
export type ErrorContext = __ErrorContextInterface<typeof REMOTE_MODULE>;
/** The subscription handle type to manage active subscriptions created from a {@link SubscriptionBuilder}. */
export type SubscriptionHandle = __SubscriptionHandleImpl<typeof REMOTE_MODULE>;

/** Builder class to configure a new subscription to the remote SpacetimeDB instance. */
export class SubscriptionBuilder extends __SubscriptionBuilderImpl<typeof REMOTE_MODULE> {}

/** Builder class to configure a new database connection to the remote SpacetimeDB instance. */
export class DbConnectionBuilder extends __DbConnectionBuilder<DbConnection> {}

/** The typed database connection to manage connections to the remote SpacetimeDB instance. This class has type information specific to the generated module. */
export class DbConnection extends __DbConnectionImpl<typeof REMOTE_MODULE> {
  /** Creates a new {@link DbConnectionBuilder} to configure and connect to the remote SpacetimeDB instance. */
  static builder = (): DbConnectionBuilder => {
    return new DbConnectionBuilder(REMOTE_MODULE, (config: __DbConnectionConfig<typeof REMOTE_MODULE>) => new DbConnection(config));
  };

  /** Creates a new {@link SubscriptionBuilder} to configure a subscription to the remote SpacetimeDB instance. */
  override subscriptionBuilder = (): SubscriptionBuilder => {
    return new SubscriptionBuilder(this);
  };
}

