// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  codeLigne: __t.string().primaryKey().name("code_ligne"),
  pictoMode: __t.option(__t.string()).name("picto_mode"),
  pictoLigne: __t.option(__t.string()).name("picto_ligne"),
  pictoComplet: __t.option(__t.string()).name("picto_complet"),
});
