// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  lineName: __t.option(__t.string()).name("line_name"),
  traceCode: __t.option(__t.string()).name("trace_code"),
  lineCode: __t.option(__t.string()).name("line_code"),
  traceType: __t.option(__t.string()).name("trace_type"),
  traceName: __t.option(__t.string()).name("trace_name"),
  direction: __t.option(__t.string()),
  originId: __t.option(__t.string()).name("origin_id"),
  destinationId: __t.option(__t.string()).name("destination_id"),
  originName: __t.option(__t.string()).name("origin_name"),
  destinationName: __t.option(__t.string()).name("destination_name"),
  transportFamily: __t.option(__t.string()).name("transport_family"),
  startDate: __t.option(__t.string()).name("start_date"),
  endDate: __t.option(__t.string()).name("end_date"),
  lineTypeCode: __t.option(__t.string()).name("line_type_code"),
  lineTypeName: __t.option(__t.string()).name("line_type_name"),
  pmrAccessible: __t.option(__t.bool()).name("pmr_accessible"),
  lineSortCode: __t.option(__t.string()).name("line_sort_code"),
  versionName: __t.option(__t.string()).name("version_name"),
  lastUpdate: __t.option(__t.string()).name("last_update"),
  category: __t.option(__t.string()),
  color: __t.option(__t.string()),
});
