// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.i64().primaryKey(),
  address: __t.option(__t.string()),
  communeInsee: __t.option(__t.string()).name("commune_insee"),
  infoLocation: __t.option(__t.string()).name("info_location"),
  provenance: __t.option(__t.string()),
  latitude: __t.f64(),
  longitude: __t.f64(),
  recordedAt: __t.timestamp().name("recorded_at"),
});
