// @ts-nocheck
// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "../spacetimedb-shim";

export default __t.row({
  id: __t.string().primaryKey(),
  stationApiId: __t.option(__t.i64()).name("station_api_id"),
  stationId: __t.option(__t.i64()).name("station_id"),
  name: __t.option(__t.string()),
  serviceInfo: __t.option(__t.string()).name("service_info"),
  lastUpdate: __t.option(__t.string()).name("last_update"),
  longitude: __t.option(__t.f64()),
  latitude: __t.option(__t.f64()),
});
