// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  name: __t.option(__t.string()),
  serviceInfo: __t.option(__t.string()).name("service_info"),
  pmrAccessible: __t.option(__t.bool()).name("pmr_accessible"),
  hasElevator: __t.option(__t.bool()).name("has_elevator"),
  hasEscalator: __t.option(__t.bool()).name("has_escalator"),
  lastUpdate: __t.option(__t.string()).name("last_update"),
  address: __t.option(__t.string()),
  municipality: __t.option(__t.string()),
  latitude: __t.option(__t.f64()),
  longitude: __t.option(__t.f64()),
  zone: __t.option(__t.string()),
  gtfsStopId: __t.option(__t.string()).name("gtfs_stop_id"),
});
