// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Alert = __t.object("Alert", {
  alertKey: __t.string(),
  alertId: __t.option(__t.i64()),
  alertType: __t.option(__t.string()),
  cause: __t.option(__t.string()),
  startTime: __t.option(__t.string()),
  endTime: __t.option(__t.string()),
  mode: __t.option(__t.string()),
  lineCommercialName: __t.option(__t.string()),
  lineCustomerName: __t.option(__t.string()),
  title: __t.option(__t.string()),
  message: __t.option(__t.string()),
  lastUpdate: __t.option(__t.string()),
  severityType: __t.option(__t.string()),
  severityLevel: __t.option(__t.i64()),
  objectType: __t.option(__t.string()),
  objectList: __t.option(__t.string()),
});
export type Alert = __Infer<typeof Alert>;

export const AutopartageStation = __t.object("AutopartageStation", {
  idStation: __t.string(),
  name: __t.string(),
  address: __t.option(__t.string()),
  commune: __t.option(__t.string()),
  latitude: __t.f64(),
  longitude: __t.f64(),
  nbEmplacements: __t.i64(),
  typeAutopartage: __t.option(__t.string()),
  lastUpdate: __t.option(__t.string()),
  recordedAt: __t.timestamp(),
});
export type AutopartageStation = __Infer<typeof AutopartageStation>;

export const Config = __t.object("Config", {
  id: __t.u64(),
  tclApiToken: __t.option(__t.string()),
  gtfsZipUrl: __t.option(__t.string()),
});
export type Config = __Infer<typeof Config>;

export const ConfigUpdate = __t.object("ConfigUpdate", {
  tclApiToken: __t.option(__t.string()),
  gtfsZipUrl: __t.option(__t.string()),
});
export type ConfigUpdate = __Infer<typeof ConfigUpdate>;

export const ConfigUpdatePlain = __t.object("ConfigUpdatePlain", {
  tclApiToken: __t.string(),
  gtfsZipUrl: __t.string(),
});
export type ConfigUpdatePlain = __Infer<typeof ConfigUpdatePlain>;

export const EstimatedCallCurrent = __t.object("EstimatedCallCurrent", {
  callId: __t.string(),
  recordedAtTime: __t.timestamp(),
  datedVehicleJourneyRef: __t.string(),
  stopPointRef: __t.option(__t.string()),
  gtfsStopId: __t.option(__t.string()),
  stopPointName: __t.option(__t.string()),
  aimedArrivalTime: __t.option(__t.string()),
  expectedArrivalTime: __t.option(__t.string()),
  aimedDepartureTime: __t.option(__t.string()),
  expectedDepartureTime: __t.option(__t.string()),
  stopOrder: __t.option(__t.i64()),
});
export type EstimatedCallCurrent = __Infer<typeof EstimatedCallCurrent>;

export const EstimatedVehicleJourneyCurrent = __t.object("EstimatedVehicleJourneyCurrent", {
  datedVehicleJourneyRef: __t.string(),
  recordedAtTime: __t.timestamp(),
  lineRef: __t.option(__t.string()),
  directionRef: __t.option(__t.string()),
  destinationRef: __t.option(__t.string()),
  lineSortCode: __t.option(__t.string()),
});
export type EstimatedVehicleJourneyCurrent = __Infer<typeof EstimatedVehicleJourneyCurrent>;

export const GtfsAgency = __t.object("GtfsAgency", {
  agencyId: __t.string(),
  agencyName: __t.option(__t.string()),
  agencyUrl: __t.option(__t.string()),
  agencyTimezone: __t.option(__t.string()),
  agencyLang: __t.option(__t.string()),
  agencyPhone: __t.option(__t.string()),
  agencyFareUrl: __t.option(__t.string()),
  agencyEmail: __t.option(__t.string()),
});
export type GtfsAgency = __Infer<typeof GtfsAgency>;

export const GtfsCalendar = __t.object("GtfsCalendar", {
  serviceId: __t.string(),
  monday: __t.option(__t.string()),
  tuesday: __t.option(__t.string()),
  wednesday: __t.option(__t.string()),
  thursday: __t.option(__t.string()),
  friday: __t.option(__t.string()),
  saturday: __t.option(__t.string()),
  sunday: __t.option(__t.string()),
  startDate: __t.option(__t.string()),
  endDate: __t.option(__t.string()),
});
export type GtfsCalendar = __Infer<typeof GtfsCalendar>;

export const GtfsCalendarDate = __t.object("GtfsCalendarDate", {
  calendarDateId: __t.string(),
  serviceId: __t.option(__t.string()),
  date: __t.option(__t.string()),
  exceptionType: __t.option(__t.string()),
});
export type GtfsCalendarDate = __Infer<typeof GtfsCalendarDate>;

export const GtfsFeedInfo = __t.object("GtfsFeedInfo", {
  feedId: __t.u64(),
  feedPublisherName: __t.option(__t.string()),
  feedPublisherUrl: __t.option(__t.string()),
  feedLang: __t.option(__t.string()),
  feedStartDate: __t.option(__t.string()),
  feedEndDate: __t.option(__t.string()),
  feedVersion: __t.option(__t.string()),
});
export type GtfsFeedInfo = __Infer<typeof GtfsFeedInfo>;

export const GtfsRoute = __t.object("GtfsRoute", {
  routeId: __t.string(),
  agencyId: __t.option(__t.string()),
  routeShortName: __t.option(__t.string()),
  routeLongName: __t.option(__t.string()),
  routeDesc: __t.option(__t.string()),
  routeType: __t.option(__t.string()),
  routeUrl: __t.option(__t.string()),
  routeColor: __t.option(__t.string()),
  routeTextColor: __t.option(__t.string()),
  routeSortOrder: __t.option(__t.string()),
});
export type GtfsRoute = __Infer<typeof GtfsRoute>;

export const GtfsShape = __t.object("GtfsShape", {
  shapePointId: __t.string(),
  shapeId: __t.option(__t.string()),
  shapePtLat: __t.option(__t.string()),
  shapePtLon: __t.option(__t.string()),
  shapePtSequence: __t.option(__t.string()),
  shapeDistTraveled: __t.option(__t.string()),
});
export type GtfsShape = __Infer<typeof GtfsShape>;

export const GtfsStop = __t.object("GtfsStop", {
  stopId: __t.string(),
  stopCode: __t.option(__t.string()),
  stopName: __t.option(__t.string()),
  stopDesc: __t.option(__t.string()),
  stopLat: __t.option(__t.string()),
  stopLon: __t.option(__t.string()),
  zoneId: __t.option(__t.string()),
  stopUrl: __t.option(__t.string()),
  locationType: __t.option(__t.string()),
  parentStation: __t.option(__t.string()),
  stopTimezone: __t.option(__t.string()),
  wheelchairBoarding: __t.option(__t.string()),
  levelId: __t.option(__t.string()),
  platformCode: __t.option(__t.string()),
});
export type GtfsStop = __Infer<typeof GtfsStop>;

export const GtfsStopTime = __t.object("GtfsStopTime", {
  stopTimeId: __t.string(),
  tripId: __t.option(__t.string()),
  arrivalTime: __t.option(__t.string()),
  departureTime: __t.option(__t.string()),
  stopId: __t.option(__t.string()),
  stopSequence: __t.option(__t.string()),
  stopHeadsign: __t.option(__t.string()),
  pickupType: __t.option(__t.string()),
  dropOffType: __t.option(__t.string()),
  shapeDistTraveled: __t.option(__t.string()),
  timepoint: __t.option(__t.string()),
});
export type GtfsStopTime = __Infer<typeof GtfsStopTime>;

export const GtfsTransfer = __t.object("GtfsTransfer", {
  transferId: __t.string(),
  fromStopId: __t.option(__t.string()),
  toStopId: __t.option(__t.string()),
  transferType: __t.option(__t.string()),
  minTransferTime: __t.option(__t.string()),
});
export type GtfsTransfer = __Infer<typeof GtfsTransfer>;

export const GtfsTrip = __t.object("GtfsTrip", {
  tripId: __t.string(),
  routeId: __t.option(__t.string()),
  serviceId: __t.option(__t.string()),
  tripHeadsign: __t.option(__t.string()),
  tripShortName: __t.option(__t.string()),
  directionId: __t.option(__t.string()),
  blockId: __t.option(__t.string()),
  shapeId: __t.option(__t.string()),
  wheelchairAccessible: __t.option(__t.string()),
  bikesAllowed: __t.option(__t.string()),
});
export type GtfsTrip = __Infer<typeof GtfsTrip>;

export const IngestRequest = __t.object("IngestRequest", {});
export type IngestRequest = __Infer<typeof IngestRequest>;

export const IngestionRun = __t.object("IngestionRun", {
  id: __t.u64(),
  jobName: __t.string(),
  startedAt: __t.timestamp(),
  endedAt: __t.timestamp(),
  status: __t.string(),
  rowsUpserted: __t.u64(),
  error: __t.option(__t.string()),
});
export type IngestionRun = __Infer<typeof IngestionRun>;

export const JourneyRequest = __t.object("JourneyRequest", {
  fromLat: __t.f64(),
  fromLng: __t.f64(),
  toLat: __t.f64(),
  toLng: __t.f64(),
  datetime: __t.string(),
  isArrivalTime: __t.bool(),
  transportModes: __t.string(),
  walk: __t.string(),
  bike: __t.option(__t.string()),
  pmr: __t.bool(),
  car: __t.bool(),
  dataFreshness: __t.string(),
});
export type JourneyRequest = __Infer<typeof JourneyRequest>;

export const Line = __t.object("Line", {
  id: __t.string(),
  lineName: __t.option(__t.string()),
  traceCode: __t.option(__t.string()),
  lineCode: __t.option(__t.string()),
  traceType: __t.option(__t.string()),
  traceName: __t.option(__t.string()),
  direction: __t.option(__t.string()),
  originId: __t.option(__t.string()),
  destinationId: __t.option(__t.string()),
  originName: __t.option(__t.string()),
  destinationName: __t.option(__t.string()),
  transportFamily: __t.option(__t.string()),
  startDate: __t.option(__t.string()),
  endDate: __t.option(__t.string()),
  lineTypeCode: __t.option(__t.string()),
  lineTypeName: __t.option(__t.string()),
  pmrAccessible: __t.option(__t.bool()),
  lineSortCode: __t.option(__t.string()),
  versionName: __t.option(__t.string()),
  lastUpdate: __t.option(__t.string()),
  category: __t.option(__t.string()),
  color: __t.option(__t.string()),
});
export type Line = __Infer<typeof Line>;

export const LineIconMapping = __t.object("LineIconMapping", {
  codeLigne: __t.string(),
  pictoMode: __t.option(__t.string()),
  pictoLigne: __t.option(__t.string()),
  pictoComplet: __t.option(__t.string()),
});
export type LineIconMapping = __Infer<typeof LineIconMapping>;

export const PricingZones = __t.object("PricingZones", {
  id: __t.u64(),
  geojson: __t.string(),
  lastUpdate: __t.timestamp(),
});
export type PricingZones = __Infer<typeof PricingZones>;

export const PublicToilet = __t.object("PublicToilet", {
  id: __t.i64(),
  address: __t.option(__t.string()),
  communeInsee: __t.option(__t.string()),
  infoLocation: __t.option(__t.string()),
  provenance: __t.option(__t.string()),
  latitude: __t.f64(),
  longitude: __t.f64(),
  recordedAt: __t.timestamp(),
});
export type PublicToilet = __Infer<typeof PublicToilet>;

export const RealtimePayload = __t.object("RealtimePayload", {
  vehicles: __t.string(),
  timetables: __t.string(),
});
export type RealtimePayload = __Infer<typeof RealtimePayload>;

export const StaticPayload = __t.object("StaticPayload", {
  alerts: __t.string(),
  stations: __t.string(),
  stops: __t.string(),
  linesBus: __t.string(),
  linesMetro: __t.string(),
  linesTram: __t.string(),
  linesRhonexpress: __t.string(),
  pricingZones: __t.string(),
});
export type StaticPayload = __Infer<typeof StaticPayload>;

export const Station = __t.object("Station", {
  id: __t.string(),
  stationApiId: __t.option(__t.i64()),
  stationId: __t.option(__t.i64()),
  name: __t.option(__t.string()),
  serviceInfo: __t.option(__t.string()),
  lastUpdate: __t.option(__t.string()),
  longitude: __t.option(__t.f64()),
  latitude: __t.option(__t.f64()),
});
export type Station = __Infer<typeof Station>;

export const Stop = __t.object("Stop", {
  id: __t.string(),
  name: __t.option(__t.string()),
  serviceInfo: __t.option(__t.string()),
  pmrAccessible: __t.option(__t.bool()),
  hasElevator: __t.option(__t.bool()),
  hasEscalator: __t.option(__t.bool()),
  lastUpdate: __t.option(__t.string()),
  address: __t.option(__t.string()),
  municipality: __t.option(__t.string()),
  latitude: __t.option(__t.f64()),
  longitude: __t.option(__t.f64()),
  zone: __t.option(__t.string()),
  gtfsStopId: __t.option(__t.string()),
});
export type Stop = __Infer<typeof Stop>;

export const StopRefNameCache = __t.object("StopRefNameCache", {
  stopRef: __t.string(),
  stopName: __t.option(__t.string()),
  recordedAt: __t.timestamp(),
});
export type StopRefNameCache = __Infer<typeof StopRefNameCache>;

export const VehiclePositionCurrent = __t.object("VehiclePositionCurrent", {
  vehicleRef: __t.string(),
  recordedAtTime: __t.timestamp(),
  validUntilTime: __t.option(__t.string()),
  lineRef: __t.option(__t.string()),
  directionRef: __t.option(__t.string()),
  datedVehicleJourneyRef: __t.option(__t.string()),
  publishedLineName: __t.option(__t.string()),
  directionName: __t.option(__t.string()),
  operatorRef: __t.option(__t.string()),
  destinationRef: __t.option(__t.string()),
  destinationName: __t.option(__t.string()),
  longitude: __t.option(__t.f64()),
  latitude: __t.option(__t.f64()),
  bearing: __t.option(__t.f64()),
  delay: __t.option(__t.string()),
  stopPointRef: __t.option(__t.string()),
  stopPointName: __t.option(__t.string()),
  aimedArrivalTime: __t.option(__t.string()),
  expectedArrivalTime: __t.option(__t.string()),
  aimedDepartureTime: __t.option(__t.string()),
  expectedDepartureTime: __t.option(__t.string()),
  distanceFromStop: __t.option(__t.i64()),
  stopOrder: __t.option(__t.i64()),
  velocity: __t.option(__t.f64()),
  occupancy: __t.option(__t.string()),
});
export type VehiclePositionCurrent = __Infer<typeof VehiclePositionCurrent>;

export const VelovStation = __t.object("VelovStation", {
  number: __t.i64(),
  name: __t.string(),
  address: __t.option(__t.string()),
  commune: __t.option(__t.string()),
  latitude: __t.f64(),
  longitude: __t.f64(),
  status: __t.option(__t.string()),
  availability: __t.option(__t.string()),
  bikeStands: __t.i64(),
  availableBikeStands: __t.i64(),
  availableBikes: __t.i64(),
  availableElectricalBikes: __t.option(__t.i64()),
  availableMechanicalBikes: __t.option(__t.i64()),
  banking: __t.bool(),
  bonus: __t.bool(),
  lastUpdate: __t.option(__t.string()),
  recordedAt: __t.timestamp(),
});
export type VelovStation = __Infer<typeof VelovStation>;

