// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  vehicleRef: __t.string().primaryKey().name("vehicle_ref"),
  recordedAtTime: __t.timestamp().name("recorded_at_time"),
  validUntilTime: __t.option(__t.string()).name("valid_until_time"),
  lineRef: __t.option(__t.string()).name("line_ref"),
  directionRef: __t.option(__t.string()).name("direction_ref"),
  datedVehicleJourneyRef: __t.option(__t.string()).name("dated_vehicle_journey_ref"),
  publishedLineName: __t.option(__t.string()).name("published_line_name"),
  directionName: __t.option(__t.string()).name("direction_name"),
  operatorRef: __t.option(__t.string()).name("operator_ref"),
  destinationRef: __t.option(__t.string()).name("destination_ref"),
  destinationName: __t.option(__t.string()).name("destination_name"),
  longitude: __t.option(__t.f64()),
  latitude: __t.option(__t.f64()),
  bearing: __t.option(__t.f64()),
  delay: __t.option(__t.string()),
  stopPointRef: __t.option(__t.string()).name("stop_point_ref"),
  stopPointName: __t.option(__t.string()).name("stop_point_name"),
  aimedArrivalTime: __t.option(__t.string()).name("aimed_arrival_time"),
  expectedArrivalTime: __t.option(__t.string()).name("expected_arrival_time"),
  aimedDepartureTime: __t.option(__t.string()).name("aimed_departure_time"),
  expectedDepartureTime: __t.option(__t.string()).name("expected_departure_time"),
  distanceFromStop: __t.option(__t.i64()).name("distance_from_stop"),
  stopOrder: __t.option(__t.i64()).name("stop_order"),
  velocity: __t.option(__t.f64()),
  occupancy: __t.option(__t.string()),
});
