// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  number: __t.i64().primaryKey(),
  name: __t.string(),
  address: __t.option(__t.string()),
  commune: __t.option(__t.string()),
  latitude: __t.f64(),
  longitude: __t.f64(),
  status: __t.option(__t.string()),
  availability: __t.option(__t.string()),
  bikeStands: __t.i64().name("bike_stands"),
  availableBikeStands: __t.i64().name("available_bike_stands"),
  availableBikes: __t.i64().name("available_bikes"),
  availableElectricalBikes: __t.option(__t.i64()).name("available_electrical_bikes"),
  availableMechanicalBikes: __t.option(__t.i64()).name("available_mechanical_bikes"),
  banking: __t.bool(),
  bonus: __t.bool(),
  lastUpdate: __t.option(__t.string()).name("last_update"),
  recordedAt: __t.timestamp().name("recorded_at"),
});
