// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all procedure arg schemas
import * as CalculateJourneyProcedure from "../calculate_journey_procedure";
import * as IngestAutopartageProcedure from "../ingest_autopartage_procedure";
import * as IngestGtfsProcedure from "../ingest_gtfs_procedure";
import * as IngestPublicToiletsProcedure from "../ingest_public_toilets_procedure";
import * as IngestRealtimeProcedure from "../ingest_realtime_procedure";
import * as IngestRealtimePayloadProcedure from "../ingest_realtime_payload_procedure";
import * as IngestStaticProcedure from "../ingest_static_procedure";
import * as IngestStaticPayloadProcedure from "../ingest_static_payload_procedure";
import * as IngestVelovProcedure from "../ingest_velov_procedure";
import * as PurgeIngestionRunsProcedure from "../purge_ingestion_runs_procedure";
import * as PurgeRealtimeProcedure from "../purge_realtime_procedure";
import * as SetConfigProcedure from "../set_config_procedure";
import * as SetConfigPlainProcedure from "../set_config_plain_procedure";

export type CalculateJourneyArgs = __Infer<typeof CalculateJourneyProcedure.params>;
export type CalculateJourneyResult = __Infer<typeof CalculateJourneyProcedure.returnType>;
export type IngestAutopartageArgs = __Infer<typeof IngestAutopartageProcedure.params>;
export type IngestAutopartageResult = __Infer<typeof IngestAutopartageProcedure.returnType>;
export type IngestGtfsArgs = __Infer<typeof IngestGtfsProcedure.params>;
export type IngestGtfsResult = __Infer<typeof IngestGtfsProcedure.returnType>;
export type IngestPublicToiletsArgs = __Infer<typeof IngestPublicToiletsProcedure.params>;
export type IngestPublicToiletsResult = __Infer<typeof IngestPublicToiletsProcedure.returnType>;
export type IngestRealtimeArgs = __Infer<typeof IngestRealtimeProcedure.params>;
export type IngestRealtimeResult = __Infer<typeof IngestRealtimeProcedure.returnType>;
export type IngestRealtimePayloadArgs = __Infer<typeof IngestRealtimePayloadProcedure.params>;
export type IngestRealtimePayloadResult = __Infer<typeof IngestRealtimePayloadProcedure.returnType>;
export type IngestStaticArgs = __Infer<typeof IngestStaticProcedure.params>;
export type IngestStaticResult = __Infer<typeof IngestStaticProcedure.returnType>;
export type IngestStaticPayloadArgs = __Infer<typeof IngestStaticPayloadProcedure.params>;
export type IngestStaticPayloadResult = __Infer<typeof IngestStaticPayloadProcedure.returnType>;
export type IngestVelovArgs = __Infer<typeof IngestVelovProcedure.params>;
export type IngestVelovResult = __Infer<typeof IngestVelovProcedure.returnType>;
export type PurgeIngestionRunsArgs = __Infer<typeof PurgeIngestionRunsProcedure.params>;
export type PurgeIngestionRunsResult = __Infer<typeof PurgeIngestionRunsProcedure.returnType>;
export type PurgeRealtimeArgs = __Infer<typeof PurgeRealtimeProcedure.params>;
export type PurgeRealtimeResult = __Infer<typeof PurgeRealtimeProcedure.returnType>;
export type SetConfigArgs = __Infer<typeof SetConfigProcedure.params>;
export type SetConfigResult = __Infer<typeof SetConfigProcedure.returnType>;
export type SetConfigPlainArgs = __Infer<typeof SetConfigPlainProcedure.params>;
export type SetConfigPlainResult = __Infer<typeof SetConfigPlainProcedure.returnType>;

