// @ts-nocheck
// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "../spacetimedb-shim";

// Import all procedure arg schemas
import * as CalculateJourneyProcedure from "../calculate_journey_procedure";
import * as SetConfigProcedure from "../set_config_procedure";

export type CalculateJourneyArgs = __Infer<typeof CalculateJourneyProcedure.params>;
export type CalculateJourneyResult = __Infer<typeof CalculateJourneyProcedure.returnType>;
export type SetConfigArgs = __Infer<typeof SetConfigProcedure.params>;
export type SetConfigResult = __Infer<typeof SetConfigProcedure.returnType>;

